version: '3'
services:
  db:
    image: postgres
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: ${POSTGRES_HOST_DEV}
      DATABASE_USERNAME: ${POSTGRES_USER_PROD}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_HOST_DEV}
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"